DOMAIN-SET,https://ruleset.skk.moe/List/domainset/reject.conf,REJECT,extended-matching,pre-matching
DOMAIN-SET,https://ruleset.skk.moe/List/domainset/reject_extra.conf,REJECT,pre-matching
RULE-SET,https://ruleset.skk.moe/List/non_ip/reject.conf,REJECT,extended-matching,pre-matching
RULE-SET,https://ruleset.skk.moe/List/non_ip/reject-no-drop.conf,REJECT-NO-DROP,extended-matching,pre-matching
RULE-SET,https://ruleset.skk.moe/List/non_ip/reject-drop.conf,REJECT-DROP,pre-matching
RULE-SET,https://ruleset.skk.moe/List/ip/reject.conf,REJECT-DROP

DOMAIN,apple-relay.apple.com,Proxy,extended-matching
DOMAIN,apple-relay.cloudflare.com,Proxy,extended-matching
DOMAIN,apple-relay.fastly-edge.com,Proxy,extended-matching
DOMAIN,apple-relay.mask.apple-dns.net,Proxy,extended-matching
DOMAIN,cp4.cloudflare.com,Proxy,extended-matching
DOMAIN,gspe1-ssl.ls.apple.com,Proxy,extended-matching
# ChatGPT Voice: https://openai.com/chatgpt-voice.json (verified 2026-10-02)
IP-CIDR,102.37.57.54/32,Proxy,no-resolve
IP-CIDR,13.71.25.29/32,Proxy,no-resolve
IP-CIDR,135.220.40.201/32,Proxy,no-resolve
IP-CIDR,172.203.39.49/32,Proxy,no-resolve
IP-CIDR,172.207.173.200/32,Proxy,no-resolve
IP-CIDR,172.214.226.198/32,Proxy,no-resolve
IP-CIDR,191.233.251.27/32,Proxy,no-resolve
IP-CIDR,20.162.96.163/32,Proxy,no-resolve
IP-CIDR,20.168.48.117/32,Proxy,no-resolve
IP-CIDR,20.184.36.134/32,Proxy,no-resolve
IP-CIDR,20.203.144.245/32,Proxy,no-resolve
IP-CIDR,20.74.221.21/32,Proxy,no-resolve
IP-CIDR,4.151.200.38/32,Proxy,no-resolve
IP-CIDR,4.155.146.196/32,Proxy,no-resolve
IP-CIDR,4.197.172.116/32,Proxy,no-resolve
IP-CIDR,4.217.235.100/32,Proxy,no-resolve
IP-CIDR,4.245.198.13/32,Proxy,no-resolve
IP-CIDR,40.118.236.137/32,Proxy,no-resolve
IP-CIDR,51.4.112.173/32,Proxy,no-resolve
IP-CIDR,52.143.181.161/32,Proxy,no-resolve
IP-CIDR,68.155.152.41/32,Proxy,no-resolve
IP-CIDR,72.146.20.246/32,Proxy,no-resolve
IP-CIDR,74.248.148.7/32,Proxy,no-resolve
DOMAIN-SUFFIX,cn-ssl.ls.apple.com,DIRECT,extended-matching
DOMAIN-SUFFIX,cn.ls.apple.com,DIRECT,extended-matching
DOMAIN-SUFFIX,gspe19-cn-ssl.ls.apple.com,DIRECT,extended-matching
RULE-SET,https://ruleset.skk.moe/List/non_ip/domestic.conf,Domestic,extended-matching
RULE-SET,https://ruleset.skk.moe/List/ip/domestic.conf,Domestic
RULE-SET,https://ruleset.skk.moe/List/ip/china_ip.conf,Domestic

DOMAIN,apps.apple.com,Proxy,extended-matching
DOMAIN-SUFFIX,store.apple.com,DIRECT,extended-matching
RULE-SET,https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Surge/Surge%203/Provider/Apple%20Push.list,Proxy,extended-matching
RULE-SET,https://github.com/Blankwonder/surge-list/raw/master/apple.list,Proxy,extended-matching
RULE-SET,SYSTEM,DIRECT
RULE-SET,LAN,DIRECT
GEOIP,CN,Domestic
FINAL,Others,dns-failed

[URL Rewrite]
"^https?:\/\/(ditu|maps).google\.cn" https://maps.google.com 302
"^https?:\/\/(www.)?(g|google)\.cn" https://www.google.com 302
